CHANGELOG.md
Ref. docker/build-push-action#87
v1 for our **setup-buildx-action** is ready.
When the repo is made public:
* If so, [add the `CODECOV_TOKEN` secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository) on the repo to be able to push coverage reports through our [test workflow](https://github.com/docker/setup-buildx-action/blob/master/.github/workflows/test.yml#L27-L33).
* Add Codecov badge to README: `[![Codecov](https://img.shields.io/codecov/c/github/docker/setup-buildx-action?logo=codecov&style=flat-square)](https://codecov.io/gh/docker/setup-buildx-action)`
=> First release

.github/workflows/test.yml, README.md
@justincormack @metcalfc  Can you [enable Codecov for this repo](https://codecov.io/gh/docker/setup-buildx-action) and also [create the `CODECOV_TOKEN` secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository) to be able to upload coverage?
=> Enable Codecov and upload coverage

.github/workflows/ci.yml, README.md, __tests__/context.test.ts, action.yml, dist/index.js, src/buildx.ts, src/context.ts, src/main.ts
=> driver-opt as array of inputs (renamed driver-opts)

dist/index.js, src/buildx.ts, src/context.ts
Ref. crazy-max/ghaction-docker-buildx#223
=> Add support for more platforms

dist/index.js, src/main.ts
Closes docker/build-push-action#154
Closes docker/build-push-action#162
Fix docker/build-push-action#126
=> Temporarly set buildkit container image to moby/buildkit:v0.8-beta

dist/index.js, src/main.ts
Ref. moby/buildkit#1754 https://github.com/docker/buildx/issues/484#issuecomment-749352728
Increase max log size to 8MB based on [GitHub Runner context](https://github.com/actions/runner/blob/fc3ca9bb92cb51850d302edb07d0baa38d4e01ed/src/Runner.Common/HostContext.cs#L49) and remove log speed limit.
=> Tweak BuildKit step log limits 

dist/index.js, src/main.ts
Looks like there is an issue with #46. Log is [always clipped](https://github.com/crazy-max/swarm-cronjob/runs/1648471670?check_suite_focus=true#step:8:121) even if the size is far from exceeding the current value (8MB):
```
#10 [linux/amd64 base 3/4] RUN wget -qO- https://github.com/goreleaser/goreleaser/releases/download/v0.149.0/goreleaser_Linux_x86_64.tar.gz | tar -zxvf - goreleaser   && mv goreleaser /usr/local/bin/goreleaser
#10 sha256:818465efb7410f63f04e4cff30dbf041fc97c0340568bc3381f0011d6be40efd
#10 0.197 
#10 0.197 [output clipped, log limit 8MiB reached]
#10 DONE 0.9s
```
Try to disable clipping but same behavior:
```
#9 [linux/amd64 base 2/4] RUN apk add --no-cache ca-certificates curl gcc file git musl-dev tar
#9 sha256:cb8a83450b2611af815f803a662bac9437cdf58fe7d6996fbcb87885 …
```
=> Revert BuildKit step log limits tweak

Dockerfile, README.md
Follow-up docker/build-push-action#299
cc @tonistiigi 
=> Enhance doc

README.md, action.yml, dist/index.js, src/context.ts, src/main.ts
Fixes #66 
Hi, as discussed on #66, this PR adds a new input named `config`. The input accepts a string that is the path for the [buildkitd daemon configuration file](https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#config).
This is my first contribution on typescript but, if I understood the flow correctly, this change should be enough to make it work. @crazy-max please let me know how we can add a test to this.
Thanks!
=> Add config input

.github/workflows/ci.yml, .github/workflows/test.yml, README.md, __tests__/buildx.test.ts, __tests__/context.test.ts, action.yml, dist/index.js, src/buildx.ts, src/context.ts, src/main.ts
Refactor builder inspection and add new outputs. In a follow-up PR we will be able to display buildkitd logs (`docker logs buildx_buildkit_${builder.node_name}`) if docker-container is used to enhance debugging.
=> Enhance builder inspection

.github/workflows/ci.yml
Follow-up #67 
We can see config is [effectively used](https://github.com/docker/setup-buildx-action/runs/2423028804?check_suite_focus=true#step:11:20):
=> Add test job for config input

.github/workflows/ci.yml, .prettierrc.json, README.md, __tests__/buildx.test.ts, __tests__/context.test.ts, __tests__/git.test.ts, __tests__/util.test.ts, codecov.yml, dist/index.js, src/buildx.ts, src/context.ts, src/git.ts, src/main.ts, src/util.ts
Closes #98 
I made some changes from what we said in #98. Now buildx will be built on-the-fly against the reference passed to `build-ref` input. Here is a workflow:
```yaml
build-ref:
runs-on: ubuntu-latest
strategy:
fail-fast: false
matrix:
ref:
- master
- refs/tags/v0.5.1
- refs/pull/648/head
steps:
-
name: Checkout
uses: actions/checkout@v2
-
name: Set up Docker Buildx
uses: docker/setup-buildx-action@v1
with:
build-ref: https://github.com/docker/buildx.git#${{ matrix.ref }}
-
name: Check version
run: |
docker buildx version
```
Run: https://github.com/docker/setup-buildx-action/runs/2963153312?check_suite_focus=true#step:3:94
cc @tonistiigi 
=> Allow building buildx from source

.github/workflows/ci.yml, __tests__/buildx.test.ts, dist/index.js, src/buildx.ts
Atm buildx version defined through Git ref is not properly cached.
=> Explicit version spec for caching

.github/dependabot.yml, .github/workflows/ci.yml, README.md, __tests__/buildx.test.ts, __tests__/context.test.ts, __tests__/fixtures/buildkitd.toml, action.yml, dist/index.js, package.json, src/buildx.ts, src/context.ts, src/main.ts, yarn.lock
Allow inline config for BuildKit in the workflow. Could be useful to load a config dynamically:
```yaml
name: ci
on:
push:
jobs:
buildx:
runs-on: ubuntu-latest
steps:
-
name: Checkout
uses: actions/checkout@v2
-
name: Set up Docker Buildx
uses: docker/setup-buildx-action@v1
with:
config-inline: |
debug = true
[registry."docker.io"]
mirrors = ["mirror.gcr.io"]
-
name: Pull
run: |
docker pull alpine:latest # will pull mirror.gcr.io/alpine:latest
```
=> Add `config-inline` input

README.md, action.yml
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> Clarify install option in example

README.md
This should provide an easy reference for users starting to use this action who want to pin versions, so that they can easily identify the different versioning pattern used by this action.
=> docs: add version pinning information to the README

README.md
Super small change, but the old link hardcoding the GHE version pointed to an outdated page with a warning at the top stating such.
=> update GH doc URL

README.md
follow-up https://github.com/docker/setup-buildx-action/issues/194#issuecomment-1407394149
=> fix action version in README

README.md
First off, thank you so much for maintaining this action!
I was looking through the README and found a tiny typo. Apologies for the overhead of a full PR to fix it; feel free to dismiss and fix in the next substantive README update you have planned.
=> nit typo in README.md, csv is comma-delimited

.github/workflows/ci.yml, src/state-helper.ts
fixes https://github.com/docker/setup-buildx-action/issues/428
=> fix keep-state not being respected
