docker/setup-buildx-action

.github/CONTRIBUTING.md, .github/workflows/test.yml, Dockerfile, __tests__/buildx.test.ts, docker-bake.hcl, hack/shell, src/docker.ts
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> add container based dev flow

.github/workflows/ci.yml, dist/index.js, src/main.ts
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> support for docker driver

Dockerfile
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> dockerfile: fix validate-yarn target

README.md
=> Use master for now

README.md
=> Add install by default example

.github/workflows/ci.yml, README.md, __tests__/buildx.test.ts, action.yml, dist/index.js, src/buildx.ts, src/context.ts, src/main.ts
=> Allow daemon side entitlements by default

.github/workflows/ci.yml, CHANGELOG.md, README.md
=> v1 mutable tag

__tests__/context.test.ts, dist/index.js, src/context.ts
=> Exclude empty items from input list

dist/index.js
=> Update generated content

dist/index.js, src/main.ts
Small improvement for better log output:
=> Group log output

.github/workflows/ci.yml, .github/workflows/labels.yml, .github/workflows/test.yml
=> Use major version of actions

dist/index.js, src/main.ts
=> Remove hardcoded buildkit container image moby/buildkit:v0.8-beta

__tests__/buildx.test.ts, dist/index.js, package.json, src/buildx.ts, src/main.ts, yarn.lock
=> Improve builder name generation

.github/workflows/ci.yml, __tests__/buildx.test.ts, dist/index.js, src/main.ts
=> Override the configured builder instance

dist/index.js, src/context.ts
=> Use `core.getBooleanInput`

__tests__/buildx.test.ts, dist/index.js, src/buildx.ts
=> Fix `docker: invalid reference format`

.github/workflows/ci.yml, .github/workflows/test.yml, README.md
follow-up https://github.com/docker/build-push-action/pull/610
=> Bump all Docker actions to latest major

README.md
Bump other action versions used in example.
=> Minor README.md update - use newer action versions

README.md, docs/advanced/buildkit-config.md, docs/advanced/install-default.md, docs/advanced/standalone.md
update and split docs as we are going to have more use cases like appending nodes and also ssh/tls authentication for remote nodes.
=> update and split docs

.github/workflows/ci.yml
follow-up https://github.com/docker/build-push-action/pull/785
=> update build-push-action to v4

README.md, docs/advanced/buildkit-config.md
follow-up https://github.com/docker/docs/pull/16765
=> docs: updates

.github/workflows/ci.yml
similar to https://github.com/docker/buildx/pull/3042
=> ci: bump to ubuntu-latest

.github/workflows/ci.yml
relates to:
* https://github.com/docker/buildx/pull/1869
* https://github.com/docker/setup-buildx-action/issues/292
=> ci: test container builder on windows

.github/workflows/ci.yml
To trigger this workflow manually
=> ci: add workflow_dispatch event

.github/workflows/ci.yml
relates to
* https://github.com/docker/setup-buildx-action/issues/270
* https://github.com/docker/build-push-action/issues/1388
=> ci: k3s test with latest buildx
